### ISSUE TITLE
Viewing a goal causes an exception

### ISSUE THREAD

**Issue by TitanNano** [plausible/analytics#1492]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

The server responds with an exception when viewing a goal.

```
Request: GET /api/stats/example.dev/utm_campaigns?period=7d&date=2021-11-26&filters=%7B%22goal%22%3A%22contact%22%7D&show_noref=false
** (exit) an exception was raised:
    ** (Clickhousex.Error) Code: 42, e.displayText() = DB::Exception: Function tuple requires at least one argument.: While processing tuple(): While processing (domain = 'example.dev') AND (start < '2021-11-26T23:00:00') AND (utm_campaign IN tuple()) (version 21.3.2.5 (official build))

        (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
        (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
        (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:629: PlausibleWeb.Api.StatsController.maybe_add_cr/6
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:254: PlausibleWeb.Api.StatsController.utm_campaigns/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.phoenix_controller_pipeline/2
```

### Expected behavior

The stats can be loaded. This might be caused by the absence of any campaign data for this goal, but we do not expect the exception, regardless of that.

### Environment

```markdown
- OS: macOS
- Browser: Firefox
- Browser Version: 95.0b11
```

**Comment by ukutaht** [comment]
Thanks for reporting!

Could you try pulling and running `v.1.4.2`? It should have a fix for this error.

**Comment by TitanNano** [comment]
@ukutaht yes! Exception no longer occurs.

**Comment by ukutaht** [comment]
Great!
