### ISSUE TITLE
500 Error when connecting Google Search Console integration

### ISSUE THREAD

**Issue by rundqvist** [plausible/analytics#2571]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Hi,

I have an issue (on docker self-hosted docker).

I followed the guides for setting up integration and entered GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET as env vars.
Clicking the "Continue with Google" button on Search Console-page in Plausible takes me to google consent screen.
After approving I'm redirected back to my domain which responds with "500 Oops! Looks like we're having server issues".

Logs from Plausible docker container:
> Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
create Plausible.ClickhouseRepo database if it doesn't exist
Creation of Db successful!
Loading plausible..
Starting dependencies..
Starting repos..
Running migrations for Elixir.Plausible.Repo
Running migrations for Elixir.Plausible.ClickhouseRepo
Migrations successful!
init-admin is deprecated and is no-op now
user registration on first launch happens via Web UI instead
15:07:33.004 [error] #PID<0.3223.0> running PlausibleWeb.Endpoint (connection #PID<0.3222.0>, stream id 1) terminated
Server: example.com:80 (http)
Request: GET /auth/google/callback?state=%5B1,%22search-console%22%5D&code=[***masked***]&scope=email%20https://www.googleapis.com/auth/webmasters.readonly%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.id/0 is undefined
        nil.id()
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:591: PlausibleWeb.AuthController.google_auth_callback/2
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:1: PlausibleWeb.AuthController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:1: PlausibleWeb.AuthController.phoenix_controller_pipeline/2
        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint."call (overridable 3)"/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.call/2
15:08:12.319 [error] #PID<0.3227.0> running PlausibleWeb.Endpoint (connection #PID<0.3222.0>, stream id 2) terminated
Server: example.com:80 (http)
Request: GET /auth/google/callback?state=%5B1,%22search-console%22%5D&code=[***masked***]&scope=email%20https://www.googleapis.com/auth/webmasters.readonly%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, %Plausible.HTTPClient.Non200Error{reason: %Finch.Response{body: %{"error" => "invalid_grant", "error_description" => "Bad Request"}, headers: [{"cache-control", "no-cache, no-store, max-age=0, must-revalidate"}, {"date", "Sat, 07 Jan 2023 15:08:12 GMT"}, {"pragma", "no-cache"}, {"expires", "Mon, 01 Jan 1990 00:00:00 GMT"}, {"content-type", "application/json; charset=utf-8"}, {"vary", "X-Origin"}, {"vary", "Referer"}, {"server", "scaffolding on HTTPServer2"}, {"x-xss-protection", "0"}, {"x-frame-options", "SAMEORIGIN"}, {"x-content-type-options", "nosniff"}, {"alt-svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""}, {"accept-ranges", "none"}, {"vary", "Origin,Accept-Encoding"}, {"transfer-encoding", "chunked"}], status: 400}}}
        (plausible 0.0.1) lib/plausible/google/http.ex:128: Plausible.Google.HTTP.fetch_access_token/1
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:565: PlausibleWeb.AuthController.google_auth_callback/2
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:1: PlausibleWeb.AuthController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:1: PlausibleWeb.AuthController.phoenix_controller_pipeline/2
        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint."call (overridable 3)"/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.call/2 

### Expected behavior

Google Search Console integration successfully setup.

### Environment

```markdown
- OS: macOS
- Browser: Safari
- Browser Version: 16.2 (18614.3.7.1.5)
```

**Comment by rundqvist** [comment]
Aaaaand solved 😄 

The "invalid_grant" response made me eventually realize what the error was.
Adding this comment in case there are anyone else having the same problem:

I have locked down access to Plausible, only allowing public access to paths `/js/script.js` and `/api/event`.
The admin interface is only accessed internally or via VPN.

So, the problem was that requesting the grant from the internal url `http://192.168.x.x` was invalid when response was received on the public url `https://stats.example.com`.

After temporarily opening up public access to the admin interface, setting up the integration, and then locking it back down I now have a working integration 👍
