### ISSUE TITLE
no Mails sending for Password reset or Invites

### ISSUE THREAD

**Issue by degoya** [plausible/analytics#3676]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

no mails sent on invite or password reset.
the install worked normally without any errors and the backend is normaly reachable.
i've triend with two different mailserver and with or without SSL (same email account has been used for the old version). 
In the Backend, when i invite someone i get a notification toast that the mail has been sent, but i didn't got any mails. 
when i look at the log i see there is a network_failure/timeout, this happens on both servers, i've triend to connect to the SMTP with STARTTLS  and the same credentials without any problems.

result of `Application.get_env(:plausible, Plausible.Mailer)`
```
[
  adapter: Bamboo.SMTPAdapter,
  server: "mail01.xxxxxxxx.net",
  hostname: "plausible.xxxxxxxx.de",
  port: "25",
  username: "plausible@xxxxxxxx.de",
  password: "xxxxxxxxx",
  tls: :if_available,
  allowed_tls_versions: [:tlsv1, :"tlsv1.1", :"tlsv1.2"],
  ssl: "false",
  retries: 2,
  no_mx_lookups: true
]

```

Error Log looks like this when i try without SSL :
```
2024-01-08T13:47:23.008123238Z Loading plausible..
2024-01-08T13:47:23.016247305Z Starting dependencies..
2024-01-08T13:47:23.087546308Z Starting repos..
2024-01-08T13:47:23.141729382Z create Plausible.Repo database if it doesn't exist
2024-01-08T13:47:23.201388775Z create Plausible.IngestRepo database if it doesn't exist
2024-01-08T13:47:23.208503852Z Creation of Db successful!
2024-01-08T13:47:23.606166176Z Loading plausible..
2024-01-08T13:47:23.612949150Z Starting dependencies..
2024-01-08T13:47:23.680875828Z Starting repos..
2024-01-08T13:47:23.731618830Z Running migrations for Elixir.Plausible.Repo
2024-01-08T13:47:23.820484576Z Running migrations for Elixir.Plausible.IngestRepo
2024-01-08T13:47:23.826596724Z Migrations successful!
2024-01-08T13:47:23.838104799Z init-admin is deprecated and is no-op now
2024-01-08T13:47:23.838125598Z user registration on first launch happens via Web UI instead

2024-01-08T13:47:56.100370421Z 13:47:56.099 [error] Task #PID<0.3624.0> started from #PID<0.3623.0> terminating

2024-01-08T13:47:56.100396580Z ** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:network_failure, 'mail01.xxxxxx.net', {:error, :timeout}}

2024-01-08T13:47:56.100401429Z (bamboo 2.2.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3

2024-01-08T13:47:56.100405837Z (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2

2024-01-08T13:47:56.100408733Z (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

2024-01-08T13:47:56.100411618Z Function: #Function<0.115084270/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>

2024-01-08T13:47:56.100414634Z Args: [] 
```

with SSL turned on i get the following error:

```
2024-01-09T15:30:42.493984478Z 15:30:42.493 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
2024-01-09T15:30:42.494015277Z Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
2024-01-09T15:30:42.494020095Z
2024-01-09T15:30:42.493984478Z 15:30:42.493 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
2024-01-09T15:30:42.494015277Z Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
2024-01-09T15:30:42.494020095Z
2024-01-09T15:30:47.495115119Z 15:30:47.494 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
2024-01-09T15:30:47.495162507Z Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
2024-01-09T15:30:47.495171545Z
2024-01-09T15:30:47.495115119Z 15:30:47.494 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
2024-01-09T15:30:47.495162507Z Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
2024-01-09T15:30:47.495171545Z
2024-01-09T15:30:52.497419756Z 15:30:52.496 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
2024-01-09T15:30:52.497471283Z Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
2024-01-09T15:30:52.497480230Z
2024-01-09T15:30:52.497419756Z 15:30:52.496 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
2024-01-09T15:30:52.497471283Z Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
2024-01-09T15:30:52.497480230Z
2024-01-09T15:30:57.499798153Z 15:30:57.498 [error] Task #PID<0.3628.0> started from #PID<0.3627.0> terminating
2024-01-09T15:30:57.499858847Z ** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:network_failure, 'mail1.xxxxxx.de', {:error, :timeout}}
2024-01-09T15:30:57.499870058Z (bamboo 2.2.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3
2024-01-09T15:30:57.499878494Z (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
2024-01-09T15:30:57.500383069Z (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2024-01-09T15:30:57.500393027Z Function: #Function<0.115084270/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
2024-01-09T15:30:57.500398899Z Args: []
```

any idea why this happens ?

### Expected behavior

mail to be sent.

### Screenshots

![grafik](https://github.com/plausible/analytics/assets/3515182/51c04ff4-4ebf-44e8-9e9d-9186ffcaa374)

![grafik](https://github.com/plausible/analytics/assets/3515182/5dca9a77-6ae3-43d2-94b5-c865c5ea76c7)

### Environment

```markdown
- Plausible 2.0 selfhosted Docker
- OS: Alpine/Docker
- Browser: FF/Chrome/Edge
- Browser Version: latest evergreen
```

**Comment by ruslandoga** [comment]
👋

The error means the SMTP host `mail1.xxxxxx.de` is not reachable from the container. It doesn't seem like abything changes with/without SSL as the error stays the same.

**Comment by degoya** [comment]
thanks for this information. I've double checked everything and found out that the Provider Hetzner disables Port 25 and 465 on all new Cloud Servers for new Customers. After contacting the Support the opend up the Ports and the mail get send like expected.

**Comment by ruslandoga** [comment]
@degoya thank you for taking the time to explain the issue and the fix! :)
