### ISSUE TITLE
Docker build fails to deploy assets

### ISSUE THREAD

**Issue by Crocmagnon** [plausible/analytics#436]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
The docker build fails on step 20/35 (master branch). Here are the logs:

```
Step 20/35 : RUN npm run deploy --prefix ./assets &&     npm run deploy --prefix ./tracker &&     mix phx.digest priv/static
 ---> Running in dc8443e76b69

> @ deploy /app/assets
> $(npm bin)/webpack --mode production

/app/assets/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module 'terser-webpack-plugin'
Require stack:
- /app/assets/webpack.config.js
- /app/assets/node_modules/webpack-cli/bin/utils/convert-argv.js
- /app/assets/node_modules/webpack-cli/bin/cli.js
- /app/assets/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/app/assets/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/app/assets/webpack.config.js:4:22)
    at Module._compile (/app/assets/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/app/assets/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/app/assets/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/app/assets/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /app/assets/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/app/assets/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /app/assets/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/app/assets/node_modules/yargs/yargs.js:576:18)
    at /app/assets/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/app/assets/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/assets/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/assets/webpack.config.js',
    '/app/assets/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/app/assets/node_modules/webpack-cli/bin/cli.js',
    '/app/assets/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ deploy: `$(npm bin)/webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-25T09_24_25_068Z-debug.log
The command '/bin/sh -c npm run deploy --prefix ./assets &&     npm run deploy --prefix ./tracker &&     mix phx.digest priv/static' returned a non-zero code: 1
```

**Expected behavior**
```
docker build -t plausible .
```

should work and build a deployable image.

**Environment (If applicable):**
 - OS: ubuntu server 20.04
 - Browser not relevant
 - Version: master branch (commit d27dad729904a4b38350259f9c460d8c78047f25)

**Comment by ukutaht** [comment]
Thanks for reporting. 8d240a50256ca578150df0caca8ad1adf268b325 should fix it, let me know if it does.

**Comment by Crocmagnon** [comment]
Yes it does 👍 Thanks for the quick fix! 😀
