### ISSUE TITLE
Clickhousex error: raise_sql_call_error

### ISSUE THREAD

**Issue by Heziode** [plausible/analytics#443]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

When I looked at my logs this morning, I came across this (this is the full log from the start of the service):

```
Loading plausible..,
Starting dependencies..,
Starting repos..,
create Plausible.Repo database if it doesn't exist,
create Plausible.ClickhouseRepo database if it doesn't exist,
eation of Db successful!,
Loading plausible..,
Starting dependencies..,
Starting repos..,
Running migrations for Elixir.Plausible.Repo,
Running migrations for Elixir.Plausible.ClickhouseRepo,
Migrations successful!,
Loading plausible..,
Starting dependencies..,
Starting repos..,
Admin user already exists. I won't override, bailing,
20:02:58.711 [error] Clickhousex.Protocol (#PID<0.4266.0>) disconnected: ** (Clickhousex.Error) closed,
20:49:12.794 [error] Clickhousex.Protocol (#PID<0.4257.0>) disconnected: ** (Clickhousex.Error) closed,
20:55:11.800 [error] Clickhousex.Protocol (#PID<0.4254.0>) disconnected: ** (Clickhousex.Error) closed,
00:02:29.076 [error] Clickhousex.Protocol (#PID<0.4266.0>) disconnected: ** (Clickhousex.Error) closed,
01:24:49.158 [error] GenServer Plausible.Event.WriteBuffer terminating,
** (Clickhousex.Error) closed,
    (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1,
    (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:502: Ecto.Adapters.SQL.insert_all/8,
    (ecto 3.4.6) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6,
    (plausible 0.0.1) lib/plausible/event/write_buffer.ex:42: Plausible.Event.WriteBuffer.handle_info/2,
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4,
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6,
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3,
Last message: :tick,
```

I made a classic installation following the doc.

**Expected behavior**
No Clickhousex or SQL error.

At first glance (this is the first time I use Plausible), this issue doesn't seems to have a big impact on the operation of Plausible since I can access to my instance.

**Comment by ukutaht** [comment]
Hey, thanks for reporting. I'm aware this happens during first boot but I haven't tackled it since it doesn't really cause a problem.

**Comment by ukutaht** [comment]
Closing this as it does not have a big impact.
