### ISSUE TITLE
"Expected Elixir.Plausible.Workers.SpikeNotifier.perform/2 to return :ok"

### ISSUE THREAD

**Issue by patschi** [plausible/analytics#517]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Steps:
1. Previously using Plausible container image based on October 2020
2. Now using custom-built docker image based on commit ef4af9249f8384aa13e747e4f6a9004d15d8705d (using official Dockerfile)
3. Now receiving following server-side error with Plausible:
```
22:30:33.895 [warn] Expected Elixir.Plausible.Workers.SpikeNotifier.perform/2 to return :ok, `{:ok, value}`, or {:error, reason}. Instead
received:

[]

The job will be considered a success.

22:38:59.780 [error] Clickhousex.Protocol (#PID<0.4446.0>) disconnected: ** (Clickhousex.Error) closed
22:38:59.783 [error] Clickhousex.Protocol (#PID<0.4450.0>) disconnected: ** (Clickhousex.Error) closed
22:45:33.943 [warn] Expected Elixir.Plausible.Workers.SpikeNotifier.perform/2 to return :ok, `{:ok, value}`, or {:error, reason}. Instead
received:

[nil, nil, nil]

The job will be considered a success.

22:52:47.618 [error] #PID<0.5307.0> running PlausibleWeb.Endpoint (connection #PID<0.5306.0>, stream id 1) terminated
Server: plausible:80 (http)
Request: GET /api/stats/domain.tld/main-graph?period=month&date=2020-12-26&filters=%7B%7D
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Date.range/2
        (elixir 1.10.4) lib/calendar/date.ex:92: Date.range(~D[2020-11-05], #DateTime<2020-11-30 22:52:47.612720+00:00 GMT Etc/Greenwich>)
        (plausible 0.0.1) lib/plausible/stats/query.ex:18: Plausible.Stats.Query.shift_back/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:80: PlausibleWeb.Api.StatsController.fetch_top_stats/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:13: PlausibleWeb.Api.StatsController.main_graph/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.phoenix_controller_pipeline/2
        (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (plausible 0.0.1) lib/plug/error_handler.ex:65: PlausibleWeb.Router.call/2
22:52:48.817 [error] Clickhousex.Protocol (#PID<0.4441.0>) disconnected: ** (Clickhousex.Error) closed
```

**Expected behavior**
Not seeing such an error/crash.

**Screenshots (If applicable)**
n/a

**Environment (If applicable):**
Docker, used official Dockerfile for custom build

**Comment by ukutaht** [comment]
The  "Expected Elixir.Plausible.Workers.SpikeNotifier.perform/2 to return :ok" is coming from a background job. It should not affect the API health in any way.

I am unable to reproduce the API error below. Can you share some details on how you got your dashboard in that state?

**Comment by patschi** [comment]
The output was shown on the first start of Plausible after updating, so the below API-related error might have been a coincidence and is not related to the warning of "SpikeNotifier".

The second error could is not re-appearing anymore, not even after multiple restarts. Maybe this is somehow related to #517?
