### ISSUE TITLE
v1.3.0 migration: `DB::Exception: Syntax error: failed at position 27: SAMPLE BY user_id`

### ISSUE THREAD

**Issue by baptisteArno** [plausible/analytics#966]
## Bug report
**Describe the bug**
When I tried to update to 1.3.0 from 1.2.0: I got the following error while running migrations:
```
       Running migrations for Elixir.Plausible.Repo
       Running migrations for Elixir.Plausible.ClickhouseRepo
       ** (Clickhousex.Error) Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 27: SAMPLE BY user_id
       . Expected one of: TTL, COLUMN, ORDER BY, SETTING, QUERY (version 20.3.8.53 (official build))
           (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
           (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
           (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:838: Ecto.Adapters.SQL.execute_ddl/4
           (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
           (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
           (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
           (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
           (stdlib 3.14) timer.erl:166: :timer.tc/1
```

**Comment by ukutaht** [comment]
Thanks for reporting.

You need to upgrade your Clickhouse version: https://github.com/plausible/analytics/discussions/927

I'll add it to the release notes as well.
